version: '3.8'

services:
  backend:
    build: ./backend
    container_name: kube-ai-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=8000
      - PROMETHEUS_URL=http://host.docker.internal:30000
      - LOKI_URL=http://host.docker.internal:3100
      - ONLY_CLUSTER_MONITORING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - C:\Users\prane\.kube:/root/.kube
      - C:\Users\prane\.minikube:/root/.minikube
    restart: unless-stopped



  frontend:
    build: ./frontend
    container_name: kube-ai-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
